feat: add support to dictate if the load balancer should be internal …
aws-samples/cdk-keycloak pull request #183
Opened 2023-02-16 02:52 UTC by adamstortz

…or internet facing

Fixes #

2023-02-16 09:27 UTC, wchaws requested changes

2023-02-16 09:27 UTC, wchaws commented on src/keycloak.ts
> +      internetFacing: props.internetFacing == null ? true : props.internetFacing,
Why not?
```
internetFacing: props.internetFacing,
```
or
```
internetFacing: props.internetFacing ?? true,
```

2023-02-16 09:27 UTC, wchaws commented on src/keycloak.ts
> +      internetFacing: props.internetFacing,
I think that should be, 
```
internetFacing: props.internetFacing ?? true,
```
because the `props.internetFacing` can be `undefined`, then your default internetFacing would be `false` from https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_elasticloadbalancingv2.ApplicationLoadBalancer.html#internetfacing

2023-02-17 03:53 UTC, stefanasseg-aws commented on src/keycloak.ts
> +      internetFacing: props.internetFacing == null ? true : props.internetFacing,
@wchaws `internetFacing: props.internetFacing` wouldn't be the same. If `props.internetFacing == undefined`, it would mean that the ALB would NOT be internet facing, which would make the ALB internal by default.
`internetFacing: props.internetFacing ?? true` would work, though.

@adamstortz Could you please make that change? Thanks!

2023-02-17 05:22 UTC, wchaws approved these changes

2023-02-17 05:23 UTC, merged