support keycloak clustered deployment using JDBC_PING for quarkus distribution
aws-samples/cdk-keycloak pull request #210
Opened 2023-10-16 00:33 UTC by hpp222

Fixes #

2023-10-16 05:43 UTC, wchaws requested changes
Please add some description about this PR which aws regions did you test.

2023-10-16 05:43 UTC, wchaws commented on src/keycloak.ts
> +      ],
Is this separate read/write instances?  Is there any reason why we need reader/writer at here?

2023-10-16 05:43 UTC, wchaws commented on src/keycloak.ts
> +      parameterGroup: rds.ParameterGroup.fromParameterGroupName(this, 'ParameterGroup', 'default.aurora-mysql8.0'),
Is there any reason why we need reader/writer at here?

2023-10-16 05:43 UTC, wchaws commented on entryPoint.txt
I think you could directly embed this file into a typescript variable

2023-10-16 05:43 UTC, wchaws commented on src/keycloak.ts
> +    let entryPoint = fs.readFileSync(path.join(__dirname, '../entryPoint.txt'), 'utf8').split(',');
Please embed the config file directly into a typescript variable

2023-10-16 05:43 UTC, wchaws commented on src/keycloak.ts
> +        INITIALIZE_SQL: 'CREATE TABLE IF NOT EXISTS JGROUPSPING (own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, ping_data VARBINARY(255), constraint PK_JGROUPSPING PRIMARY KEY (o
I don't think you need to add this ENV if DB engine is mysql. You could check this https://github.com/aws-samples/keycloak-on-aws/issues/95

2023-10-16 06:00 UTC, wchaws commented on src/keycloak.ts
> +  'aws-cn': '048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/quay/keycloak/keycloak:',
Please make sure mirror existing

2023-10-16 06:14 UTC, hpp222 commented on src/keycloak.ts
> +      parameterGroup: rds.ParameterGroup.fromParameterGroupName(this, 'ParameterGroup', 'default.aurora-mysql8.0'),
aws-cdk-lib.aws_rds.DatabaseClusterProps#instanceProps is deprecated, we should use writer and readers instead. See https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_rds-readme.html#migrating-from-instanceprops

2023-10-16 10:42 UTC, hpp222 commented on src/keycloak.ts
> +        INITIALIZE_SQL: 'CREATE TABLE IF NOT EXISTS JGROUPSPING (own_addr varchar(200) NOT NULL, cluster_name varchar(200) NOT NULL, ping_data VARBINARY(255), constraint PK_JGROUPSPING PRIMARY KEY (o
Thanks. Tests show cache-ispn-jdbc-ping.xml works without initialize_sql property for mysql engine.

2023-10-16 13:37 UTC, hpp222 commented on src/keycloak.ts
> +  'aws-cn': '048912060910.dkr.ecr.cn-northwest-1.amazonaws.com.cn/quay/keycloak/keycloak:',
I'm requesting syncing the latest versions to NWCD ECR, see [here](https://github.com/nwcdlabs/container-mirror/pull/215/files) for more information.

2023-10-17 03:54 UTC, wchaws approved these changes
LGTM

2023-10-17 05:14 UTC, merged